language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install --user codecov
  - pip install pytest-cov
script:
  - pytest tests.py --cov=codecov

after_success:
  - codecov
