language: python
python:
  - "3.7"
install:
  - pip install coverage==4.3
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coveralls
  - pip install pytest-cov
  - pip install codacy-coverage
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run -m pytest tests.py --cov-report=xml --cov=.
  - ./cc-test-reporter after-build -r 66344bea55310e5bc39a8a71683c4c2552ab064ae08e8a96ebf36f9111770bae

after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
